after_success:
- "/bin/bash ./scripts/send.sh success $DISCORD_BUILD_STATUS_WEBHOOK_URL"
after_failure:
- "/bin/bash ./scripts/send.sh failure $DISCORD_BUILD_STATUS_WEBHOOK_URL"
notifications:
  email: false
sudo: required
language: go
go:
- '1.10'
services:
- docker
jobs:
  include:
  - stage: lint
    script: make lint
  - stage: test
    script: make test
  - stage: build
    script: make build
deploy:
  skip_cleanup: true
  provider: script
  script: make deploy
  on:
    branch: master
env:
  global:
  - secure: z8wGJ7ntLIX5//VHXyrbZVEcGSpNAii8wkVYfNbX3wLJvR8BSEvBkcA7XGaWijRqyt0xpOGzacrEgIh2kFkbXgec8CWpjmCjkiTIdWLVTZfXPWaRlk+ugOyZROkPsU1Zwt+U4Qa4GGDR4YOOrl50gatCZEzJT/6lvzV2nuXknvirNZm5YI/nM8UVMungEkAFkmDXgQcWwb880xXKpoypuVk0ICBOG06xb7wMHll/NM7nqxBVSMEPPrQxdad81//CfpshhqNvZ2BBxKRSS3ZlZMjC6bvIBwSTUOPX5gZSB/HNxV6snfDNWsEeFZT0I7F2veaIgTOWxouH3ZH8YhLKi1gj880EOhxRDRp5M1y2FS/qBHKyH0uGwOIklwICcBdgc/oDkNo8jX3f7V+MX9VKE7W5/L7nNBcuT5yk/tkK0kwdafumKf0LzsN1wJDOwgtDIEDusqHUW1VODXDBNkeqv6854fw8Mdy+8k8KOaW2xR2TgkegyaJtweQeAaCiqasA8GosbUzkQf21c/zj7V2pjnDhsb2Toh+Uao01ZJutdvd1Z7mTTCEuSi/bAL1CxNBZCIOLCO01ym8A3lBugkd+YepPhX9hp57by+2qwUNItoTAluP+5H6rapVAWn0pGzOenUFAZHbVhOKbaZfYOUDcwGThkgwuro/4yewzTn8PIPE=
  - secure: x0KgOqXlzzh2UVrlTnUUXrUSMX4D6Opq4/T1zu6dWMjifY87qV6XobzoaHsiXM3va5KGlvbkhpJ3ZFCEWy6LgWmsufHBjoSIKAyUb5nLElZ04g5j9Tw0pjBDDocD1EdACIgYa3fyN+VtDjdJw/RmoZFSrNzqkzEvimvGZKo7KtMdTSD4KENc6ezYiCc+8ilr7XjT0PnjsBRwJ00+0nOyUrj4FDVx5AZbAnd3oS/odOGPbMLAoGXTb3GUXtk9ulhOE1MTm3/bObsUiUKR5dRQIgPuSRn8/iF+iEEH/TTRMHjoE7Dsi149kueHYyij/vCNXbo61ZAtxa/EbClqJxmGmdpgfA6Vl0nDbUt/iP0pOU2J4nfKzyRLBKJk9bpDjvOtEkvIFKD4fUNmcjwcve5wU85YHQnbJAOG6xUg3+aIqpYPh4/v1vEFD+BDTjl5h86UjuSBBFltDt9P+Ftv+5MImlcjt+PM1ktSOhtaAq+sABBOf5Yuuhf0T/xKvSEPgrt75Z4uhyn7WAuj+4hc1GEmHZdlhzC1vaD+C+Lng7jR+d1J1H9V8dqpKFZz1wp2KzNsc/QTCM1zoVEEBpNdiaiBpAzR+A218AIj2YjlFSzJZBqegevU4M1VzaO1TD+HvN8hrimLd7JGWZIdbF6yQtA7OkPAFbRG4AwE7H9n3u3nP/0=
  - secure: oZESliVHAzpaeR4alO8DQkccT1U8VkdlE5AhvOYeWHuwpbrpFuJfpBk0pP3FfhUFw8TcOpJN7u91gxzUmchnYrq/w89xtRR3fo2SKMJ2COe/pOKJNlKl5kpIsL77Rd8D8tW6Mll76QwF8spUxdxvgufLASDUuTdqefxbkyIxGJI3vnsECwxKlcfGGx+DYwgVYHqPkIvHDfz5n0wzGAkbEfBJdv7P8xkHRSvjyxtCpYJkrt2/lqyEUNPZJQr36TZZfyWF59qvgY3Vz+Z7GONGxdIa3v1C+O+8hvwjg8J37dTvWF2QlC6f0+YxDEA3oSTWN2TEoiSKLsw76XiXt/ogx/ByLHNwLGZb7454m0qbPdtNfPUm+rjtUwRXbop064nee1DKRGJ7sLPzWYefqwBdKmbilmBtRXp0ezWlkzJ+YOzaGgmwOqy3iEgBPNOp4OqQwp/JEJ5M2cYXYcm18zG87ovj+UxnLuKRSLoZZlJ+R1Lf+yKhnOvbXgiDbbmbo4oBM13R9pEqoELFDJVXD2RiRrI6InQXehxV10d2iRG2ID1q5ZJdkZJOEaoRG1qatKHWLrwOGH8xBsTtqN3tRN5EAtQkNHpkViV0vPmFGgPW0K7socdumquForN+tnuhRCfr/3G8qM+ht+3isGDa7Ug0M9mxRYADzcoQW+I73cGIMdw=
