after_success:
  - /bin/bash ./scripts/send.sh success $DISCORD_BUILD_STATUS_WEBHOOK_URL
after_failure:
  - /bin/bash ./scripts/send.sh failure $DISCORD_BUILD_STATUS_WEBHOOK_URL

language: go
go:
  - "1.10"

jobs:
  include:
    - stage: lint
      script: make lint
    - stage: test
      script: make test
