after_success:
- "/bin/bash ./scripts/send.sh success $DISCORD_BUILD_STATUS_WEBHOOK_URL"
after_failure:
- "/bin/bash ./scripts/send.sh failure $DISCORD_BUILD_STATUS_WEBHOOK_URL"
notifications:
  email: false
sudo: required
language: go
go:
- '1.10'
services:
- docker
jobs:
  include:
  - stage: build
    script: 
    - make lint
    - make test
    - make build
deploy:
  skip_cleanup: true
  provider: script
  script: make deploy
  on:
    branch: master
env:
  global:
    # docker password
  - secure: x0KgOqXlzzh2UVrlTnUUXrUSMX4D6Opq4/T1zu6dWMjifY87qV6XobzoaHsiXM3va5KGlvbkhpJ3ZFCEWy6LgWmsufHBjoSIKAyUb5nLElZ04g5j9Tw0pjBDDocD1EdACIgYa3fyN+VtDjdJw/RmoZFSrNzqkzEvimvGZKo7KtMdTSD4KENc6ezYiCc+8ilr7XjT0PnjsBRwJ00+0nOyUrj4FDVx5AZbAnd3oS/odOGPbMLAoGXTb3GUXtk9ulhOE1MTm3/bObsUiUKR5dRQIgPuSRn8/iF+iEEH/TTRMHjoE7Dsi149kueHYyij/vCNXbo61ZAtxa/EbClqJxmGmdpgfA6Vl0nDbUt/iP0pOU2J4nfKzyRLBKJk9bpDjvOtEkvIFKD4fUNmcjwcve5wU85YHQnbJAOG6xUg3+aIqpYPh4/v1vEFD+BDTjl5h86UjuSBBFltDt9P+Ftv+5MImlcjt+PM1ktSOhtaAq+sABBOf5Yuuhf0T/xKvSEPgrt75Z4uhyn7WAuj+4hc1GEmHZdlhzC1vaD+C+Lng7jR+d1J1H9V8dqpKFZz1wp2KzNsc/QTCM1zoVEEBpNdiaiBpAzR+A218AIj2YjlFSzJZBqegevU4M1VzaO1TD+HvN8hrimLd7JGWZIdbF6yQtA7OkPAFbRG4AwE7H9n3u3nP/0=
     # docker username
  - secure: oZESliVHAzpaeR4alO8DQkccT1U8VkdlE5AhvOYeWHuwpbrpFuJfpBk0pP3FfhUFw8TcOpJN7u91gxzUmchnYrq/w89xtRR3fo2SKMJ2COe/pOKJNlKl5kpIsL77Rd8D8tW6Mll76QwF8spUxdxvgufLASDUuTdqefxbkyIxGJI3vnsECwxKlcfGGx+DYwgVYHqPkIvHDfz5n0wzGAkbEfBJdv7P8xkHRSvjyxtCpYJkrt2/lqyEUNPZJQr36TZZfyWF59qvgY3Vz+Z7GONGxdIa3v1C+O+8hvwjg8J37dTvWF2QlC6f0+YxDEA3oSTWN2TEoiSKLsw76XiXt/ogx/ByLHNwLGZb7454m0qbPdtNfPUm+rjtUwRXbop064nee1DKRGJ7sLPzWYefqwBdKmbilmBtRXp0ezWlkzJ+YOzaGgmwOqy3iEgBPNOp4OqQwp/JEJ5M2cYXYcm18zG87ovj+UxnLuKRSLoZZlJ+R1Lf+yKhnOvbXgiDbbmbo4oBM13R9pEqoELFDJVXD2RiRrI6InQXehxV10d2iRG2ID1q5ZJdkZJOEaoRG1qatKHWLrwOGH8xBsTtqN3tRN5EAtQkNHpkViV0vPmFGgPW0K7socdumquForN+tnuhRCfr/3G8qM+ht+3isGDa7Ug0M9mxRYADzcoQW+I73cGIMdw=
    # discord webhook url
  - secure: id/5mN3xJzBHBjODn7taut9TC6kMBL4IJIYs455yHGVpyA1PoG95u7oxZAoGOY4gu29Tim3DL4+OqxVwNlMya/Vq4fOWz1glut3dU1UXWEWsRpezjiooB1+Yu3dpxcUSoOyOfEfLvzy6l781ufXJytdCoh+2wB5zOxjL87D6tYZyDTH/P4Tg/FvDZUgbZf1K1V5ygdIT4U5omtB2p4AP5NLx0tqhIb4IpGp1RGyq7Yk3/NrODuw7UAf4pFAC9Fx0bMdcPTniB6DN5q/FU2RRcvQXAy36IT6dZOiutiwoSaZDh4+yrwNA+BjHJDnOr9FjJAiN7aXlmAr/NXZCYLT/+MI1ncDzppFL7iRnBm5O9vU7hv85bJUyQiv3XF4NbkH8m6MRrkZ4e4qblYanIUcpvg3X2iV/cxuoP7BN24mb9UjJ+cXTSdZBlk6tQu956DwGR+i5hMKlwPcM29ErghFDUqR9IlogVa7l2NGt9z8iQ+AMeBOQx0y/sNNDh5N/gPypxlJkNJK4quOrzqy+BlYkZKi6IoyYJfkcvuVmB16bC0Eyz4epDyAJLXl7I0+tkQRdzGhari0NGA5ic7V/1dUInRVwWBgPGV/OzFxgh1UZ/o8Kl17Y9u/xnKr0xgPCuFQYxK6Fxu0AS3zxwIqXYVDJjEi567zTziFYZ4KHZOlS8Hs=
