// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commands.proto

package commands

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InboundMessage struct {
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	RawMessage           string               `protobuf:"bytes,2,opt,name=RawMessage,proto3" json:"RawMessage,omitempty"`
	Command              string               `protobuf:"bytes,3,opt,name=Command,proto3" json:"Command,omitempty"`
	Arguments            []string             `protobuf:"bytes,4,rep,name=Arguments,proto3" json:"Arguments,omitempty"`
	DiscordUserID        string               `protobuf:"bytes,5,opt,name=DiscordUserID,proto3" json:"DiscordUserID,omitempty"`
	DiscordMessageID     string               `protobuf:"bytes,6,opt,name=DiscordMessageID,proto3" json:"DiscordMessageID,omitempty"`
	DiscordChannelID     string               `protobuf:"bytes,7,opt,name=DiscordChannelID,proto3" json:"DiscordChannelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InboundMessage) Reset()         { *m = InboundMessage{} }
func (m *InboundMessage) String() string { return proto.CompactTextString(m) }
func (*InboundMessage) ProtoMessage()    {}
func (*InboundMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_61773289d0b853f4, []int{0}
}
func (m *InboundMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InboundMessage.Unmarshal(m, b)
}
func (m *InboundMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InboundMessage.Marshal(b, m, deterministic)
}
func (dst *InboundMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InboundMessage.Merge(dst, src)
}
func (m *InboundMessage) XXX_Size() int {
	return xxx_messageInfo_InboundMessage.Size(m)
}
func (m *InboundMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_InboundMessage.DiscardUnknown(m)
}

var xxx_messageInfo_InboundMessage proto.InternalMessageInfo

func (m *InboundMessage) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *InboundMessage) GetRawMessage() string {
	if m != nil {
		return m.RawMessage
	}
	return ""
}

func (m *InboundMessage) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *InboundMessage) GetArguments() []string {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *InboundMessage) GetDiscordUserID() string {
	if m != nil {
		return m.DiscordUserID
	}
	return ""
}

func (m *InboundMessage) GetDiscordMessageID() string {
	if m != nil {
		return m.DiscordMessageID
	}
	return ""
}

func (m *InboundMessage) GetDiscordChannelID() string {
	if m != nil {
		return m.DiscordChannelID
	}
	return ""
}

type OutboundMessage struct {
	DiscordUserID        string   `protobuf:"bytes,1,opt,name=DiscordUserID,proto3" json:"DiscordUserID,omitempty"`
	DiscordChannelID     string   `protobuf:"bytes,2,opt,name=DiscordChannelID,proto3" json:"DiscordChannelID,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutboundMessage) Reset()         { *m = OutboundMessage{} }
func (m *OutboundMessage) String() string { return proto.CompactTextString(m) }
func (*OutboundMessage) ProtoMessage()    {}
func (*OutboundMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_commands_61773289d0b853f4, []int{1}
}
func (m *OutboundMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutboundMessage.Unmarshal(m, b)
}
func (m *OutboundMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutboundMessage.Marshal(b, m, deterministic)
}
func (dst *OutboundMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutboundMessage.Merge(dst, src)
}
func (m *OutboundMessage) XXX_Size() int {
	return xxx_messageInfo_OutboundMessage.Size(m)
}
func (m *OutboundMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_OutboundMessage.DiscardUnknown(m)
}

var xxx_messageInfo_OutboundMessage proto.InternalMessageInfo

func (m *OutboundMessage) GetDiscordUserID() string {
	if m != nil {
		return m.DiscordUserID
	}
	return ""
}

func (m *OutboundMessage) GetDiscordChannelID() string {
	if m != nil {
		return m.DiscordChannelID
	}
	return ""
}

func (m *OutboundMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*InboundMessage)(nil), "commands.InboundMessage")
	proto.RegisterType((*OutboundMessage)(nil), "commands.OutboundMessage")
}

func init() { proto.RegisterFile("commands.proto", fileDescriptor_commands_61773289d0b853f4) }

var fileDescriptor_commands_61773289d0b853f4 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0xa5, 0xe4,
	0xd3, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0xc1, 0xe2, 0x49, 0xa5, 0x69, 0xfa, 0x25, 0x99, 0xb9,
	0xa9, 0xc5, 0x25, 0x89, 0xb9, 0x05, 0x10, 0xa5, 0x4a, 0x0b, 0x98, 0xb8, 0xf8, 0x3c, 0xf3, 0x92,
	0xf2, 0x4b, 0xf3, 0x52, 0x7c, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x85, 0x2c, 0xb8, 0x38, 0x43,
	0x60, 0xaa, 0x24, 0x18, 0x15, 0x18, 0x35, 0xb8, 0x8d, 0xa4, 0xf4, 0x20, 0xe6, 0xe8, 0xc1, 0xcc,
	0xd1, 0x83, 0xab, 0x08, 0x42, 0x28, 0x16, 0x92, 0xe3, 0xe2, 0x0a, 0x4a, 0x2c, 0x87, 0x9a, 0x23,
	0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x84, 0x24, 0x22, 0x24, 0xc1, 0xc5, 0xee, 0x0c, 0x71, 0x99,
	0x04, 0x33, 0x58, 0x12, 0xc6, 0x15, 0x92, 0xe1, 0xe2, 0x74, 0x2c, 0x4a, 0x2f, 0xcd, 0x4d, 0xcd,
	0x2b, 0x29, 0x96, 0x60, 0x51, 0x60, 0xd6, 0xe0, 0x0c, 0x42, 0x08, 0x08, 0xa9, 0x70, 0xf1, 0xba,
	0x64, 0x16, 0x27, 0xe7, 0x17, 0xa5, 0x84, 0x16, 0xa7, 0x16, 0x79, 0xba, 0x48, 0xb0, 0x82, 0x75,
	0xa3, 0x0a, 0x0a, 0x69, 0x71, 0x09, 0x40, 0x05, 0xa0, 0xf6, 0x79, 0xba, 0x48, 0xb0, 0x81, 0x15,
	0x62, 0x88, 0x23, 0xa9, 0x75, 0xce, 0x48, 0xcc, 0xcb, 0x4b, 0xcd, 0xf1, 0x74, 0x91, 0x60, 0x47,
	0x51, 0x0b, 0x17, 0x57, 0xaa, 0xe5, 0xe2, 0xf7, 0x2f, 0x2d, 0x41, 0x09, 0x22, 0x0c, 0x07, 0x31,
	0xe2, 0x77, 0x10, 0xc2, 0x12, 0x26, 0xec, 0x96, 0x80, 0x82, 0x06, 0x16, 0x6e, 0xd0, 0xa0, 0x81,
	0x72, 0x9d, 0xb8, 0xa2, 0xe0, 0xd1, 0x99, 0xc4, 0x06, 0x0e, 0x7f, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x70, 0xbf, 0x94, 0xb1, 0xf1, 0x01, 0x00, 0x00,
}
